language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  pip install codecov
install:
  - python setup.py develop
  - pip install pyramid_html_minifier[testing]
script:
  - py.test --tb=native --cov=pyramid_html_minifier --cov-report=term-missing
after_success:
  codecov
